### PR TITLE
Add Cytoscape layout for the Service Graph page

### PR DESCRIPTION
**Pull request by mtho11**
Preliminary Service Graph with Cytoscape

image

https://issues.jboss.org/browse/SWS-73

Next steps to hook up to Jay's live data (we have already agreed on a cytoscape data format to send).
Still need to tweak look-n-feel more, add namespace selection and linking to other screens.

### CODE REVIEW

**Comment by mtho11** [comment]
Hopefully, we can merge this quickly so everyone can start playing (since we don't have much time). And then address all concerns.

**Comment by mtho11** [comment]
Should a click on node take you to the detail page or render information about that node (say in a popup info block)?

**Comment by mtho11** [comment]
Also, in general, I guess we are going with a white background in our main page section when the patternfly sections are dark?
Seems like we should be lite or dark profile?

**Comment by mtho11** [comment]
Because we have no real wireframe mockups everyone is just making stuff up at this point. Every developer with their own style.

**Comment by theute** [comment]
White background is what we (mostly) see in OpenShift console, so +1 on white background only.
And yes, let's merge this one when reviewed that it works and improve the LnF in other iterations

**Comment by pilhuhn** [comment]
Checked out the current status locally and this shows nicely. So also +1 on merging now and refining afterwards.

**Pull request merged**
