### PR TITLE
[minor update] remove old temporary title on metrics page

### PR DESCRIPTION
**Pull request by jotak**

### CODE REVIEW

**Comment by jotak** [comment]
@lucasponce this is a very minor change just in order to look a bit better before a demo, I removed the ugly title that I put temporarily on metrics apge

**Comment by lucasponce** [comment]
LGTM

**Comment by lucasponce** [comment]
beersJoelWillPay = beersJoelWillPay + 1; :-)

**Comment by jotak** [comment]
I never signed for this rule :)

**Pull request merged**
