### PR TITLE
SWS-165: Add Namespace and navigation to incorporate namespace

### PR DESCRIPTION
**Pull request by mtho11**

### CODE REVIEW

**Comment by pilhuhn** [comment]
LGTM, but I'd like to see a review from someone with React/JS clue

**Comment by lucasponce** [comment]
This would need a rebase, I guess it is needed to check navigation tests are good for travis.

**Comment by cfcosta** [comment]
This also conflicts with #57, can you take a look at it?

**Comment by pilhuhn** [comment]
!(https://pbs.twimg.com/media/DXISxKOW4AEkqjk.jpg)

**Comment by mtho11** [comment]
Actually I will let @lucasponce and @vnugent resolve the Nav testing issue: https://github.com/swift-sunshine/swsui/blob/master/src/pages/ServiceList/ServiceListComponent.tsx#L63

**Comment by abonas** [comment]
@mtho11 @pilhuhn can we please agree to add screenshots to ui related PRs? I cannot understand what was changed/added in this PR from reading its title.

**Pull request merged**
