### PR TITLE
SWS-101 Add Coveralls

### PR DESCRIPTION
**Pull request by josejulio**
Depends on #27

### CODE REVIEW

**Comment by josejulio** [comment]
If we want coveralls we would need to signup and enable for this repository

**Comment by mtho11** [comment]
Thanks @josejulio!

**Comment by abonas** [comment]
did we agree adding Coveralls? what JIRA card is this?

**Comment by jotak** [comment]
@josejulio 

> If we want coveralls we would need to signup and enable for this repository

Isn't coveralls which generated the covering table at the end of the build logs?
If not, maybe it is sufficient?

**Comment by josejulio** [comment]
> did we agree adding Coveralls? what JIRA card is this?
[SWS-101](https://issues.jboss.org/browse/SWS-101)



> Isn't coveralls which generated the covering table at the end of the build logs?
> If not, maybe it is sufficient?

`jest` did generate the covering table (command `npm test -- --coverage`), but if we want our "badge", someone with enough perimssions needs to signup to `http://coveralls.io/` and enable for this repo.

**Comment by mtho11** [comment]
@josejulio looks like this needs rebasing

**Comment by josejulio** [comment]
> @josejulio looks like this needs rebasing

Rebased

**Comment by mtho11** [comment]
Looks like we still need someone with privs to enable for this repo and add badges
@pilhuhn is that you?

**Comment by josejulio** [comment]
Closing/Opening PR to run Travis again

**Comment by josejulio** [comment]
Travis error seems to be unrelated

**Comment by josejulio** [comment]
@pilhuhn enabled this repo on coveralls (thanks!) 

The badge can be seen here:
https://github.com/josejulio/swsui/blob/957b39099a0d275f1f924f6f14c59ab986dd8c3d/README.adoc
and our first coverage report is here:
https://coveralls.io/github/swift-sunshine/swsui?branch=master

Currently coverage is "Unknown" because is the coverage for "master", so once we merge it should show something

**Pull request merged**
