### PR TITLE
SWS-114 Add a minimal navigation

### PR DESCRIPTION
**Pull request by lucasponce**
- Define a vertical navigation
- Link with routes
- Fixes some style affecting proper components layout

Note, this is just to introduce a proper navigation into the application.
It doesn't enforce to choose vertical/horizontal but in the steps we are moving, it is good to have something.
Some rationale: I started working with the PatternFly React component but it has some bug with the Routes, so I prepared a simpler component that works (most work is just to investigate what people are doing and we are mimic the best practices defined in the patternfly react demo app).

With this, it will be easier to continue working on proper components and put things together.

### CODE REVIEW

**Comment by lucasponce** [comment]
image

image

**Comment by abonas** [comment]
@mwringe @mtho11 fyi

**Comment by lucasponce** [comment]
Locally I hit a different error, but related to the env.
Fixed in Linux like
```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```
It seems npm test needs some param in travis (probably headless related).
Still looking.

**Comment by lucasponce** [comment]
Ok, there were a couple of things here:
- prettier detect something not well formated but the error was unclear.
- Also there was a missing a build-css in travis to make tests pass.

Now it's ok.

**Comment by abonas** [comment]
nice!! please check the icons to:
service should be `pficon-service`
graph should be `pficon-topology`

**Comment by lucasponce** [comment]
> nice!! please check the icons to:
> service should be pficon-service
> graph should be pficon-topology

Those will be adjusted in a following PR, this is just for the technology used in the navigation, all labels, sections, etc are just examples.

**Pull request merged**
