### PR TITLE
SWS-119 Display Grafana link

### PR DESCRIPTION
**Pull request by jotak**
Consume api endpoint /api/grafana to get grafana info and display link on metrics page

Requires PR https://github.com/swift-sunshine/swscore/pull/69 on swscore

### CODE REVIEW

**Comment by cfcosta** [comment]
LGTM, is there any screenshots?

**Comment by lucasponce** [comment]
@jotak this needs a rebase

**Comment by jotak** [comment]
@lucasponce it's rebased
@cfcosta no screenshot, it looks so bad right now :s 
(More seriously, it's just a link added. It doesn't look "patternflyish" at the moment, but SWS-118 will remedy to that)

**Comment by lucasponce** [comment]
ok let's merge first as @aljesusg will need it to his work as well.

**Pull request merged**
