### PR TITLE
SWS-131: prefix all client routes with /console

### PR DESCRIPTION
**Pull request by jotak**
Needs https://github.com/swift-sunshine/swscore/pull/64 on server side
PS: for motivations, see discussion on server-side PR

### CODE REVIEW

**Comment by lucasponce** [comment]
mmm is this going to work with the local npm start development mode ?

**Comment by jotak** [comment]
@lucasponce yes it does. React-router does all the work (and apparently does it well)

**Comment by lucasponce** [comment]
@jotak if this is tested with the development trick to use proxy on package.json
```
  "proxy": "http://sws-istio-system.127.0.0.1.nip.io",
```
then it's fine :-). Just wanted to double check to not break the common flow of development UI + backend.

**Comment by jotak** [comment]
Just tested with proxy, I confirm it works

**Pull request merged**
