### PR TITLE
Graph layout styles

### PR DESCRIPTION
**Pull request by mtho11**
This is a visual style only request. It makes the text more readable and colors more perceptible.

styles

Also selected nodes and edges have been softened.

### CODE REVIEW

**Comment by mtho11** [comment]
@lucasponce, @jotak @aljesusg any ideas I'm going to bed. I didn't even touch those files. maybe I'm just sleepy it has been a really long day.

**Comment by pilhuhn** [comment]
@lucasponce @mtho11 I am a bit worried about the changes to package* files, but don't know enough to either approve or reject

**Comment by lucasponce** [comment]
let's wait @mtho11 about the snapshot package, it's the only potential doubt, but other changes looked ok.

**Comment by mtho11** [comment]
Hmmm I didn't change those files. I only changed the style file. It must have automerged that we I rebased. Strange.

**Comment by pilhuhn** [comment]
@mtho11 Can't you just locally roll back those changes and then send a followup commit / push -f that only has the cytoscape changes, but not the pack* files?

**Comment by josejulio** [comment]
It looks as if you you squashed up to the npm-snapshot commit.

It seems that is safe to revert the package.json and package-lock and rebase again.

**Comment by josejulio** [comment]
Closing in favor of #72 (Same code + prettier - package)

**Pull request closed without merging**
