### PR TITLE
Add Prettier to format code

### PR DESCRIPTION
**Pull request by aljesusg**
Documentation : [Link](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#formatting-code-automatically)

This command fix all project **./node_modules/.bin/prettier --single-quote --write "src/**/*.{js,jsx,json,css}"**
captura de pantalla 2018-02-14 a las 17 16 55
When you have not issues in lint
captura de pantalla 2018-02-14 a las 17 16 37
When husky fix some issues
captura de pantalla 2018-02-14 a las 17 15 59

Thanks @mtho11 for the chat ^^

### CODE REVIEW

**Comment by aljesusg** [comment]
I see that you are gonna use tsx. We can add to eslint

"rules": {
    "react/jsx-filename-extension": ["error", { "extensions": [".jsx", ".tsx"] }],
    "import/extensions": ["error", "always", {
      "js": "never",
      "jsx": "never",
      "ts": "never",
      "tsx": "never"
    }]
  },

  "settings": {
    "import/extensions": [".js", ".jsx", ".ts", ".tsx" ],
    "import/resolver": {
      "node": {
        "extensions": [".js", ".jsx", ".json", ".ts", ".tsx"]
      }
    }
  }

**Comment by mtho11** [comment]
Why not use prettier? It seems to have more traction these days?

**Comment by mtho11** [comment]
I think we also need the auto-formatting task associated with the pre-commit hook so everything is formatted -- no matter if someone forgot to format.

**Comment by aljesusg** [comment]
I add prettier too, see the actual .eslint 

"plugins": ["prettier", "react"],

**Comment by aljesusg** [comment]
I didn't know that this project will be with typescript @mtho11  I think that tslint is fine too for this. I did the proposal of eslint with the configuration for tsx too for be in the same way of patternfly-react

**Comment by mtho11** [comment]
There is also this: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#formatting-code-automatically

**Comment by mtho11** [comment]
@pilhuhn you got your [Prettier](https://prettier.io/)

**Pull request merged**
